package ec.edu.espe.alertsystem.view;

/**
 *
 * @author JOSUE
 */
public class FrmAlertSystemMenuBoss extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAlertSystemMenuBoss.class.getName());

    /**
     * Creates new form FrmAlertSystemLogin
     */
    public FrmAlertSystemMenuBoss() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuProfile = new javax.swing.JMenu();
        MnuLogOut = new javax.swing.JMenuItem();
        MnuExit = new javax.swing.JMenuItem();
        MnuClient = new javax.swing.JMenu();
        MnuManageCustomer = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MnuTask = new javax.swing.JMenu();
        MnuManageTask = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MnuAssistant = new javax.swing.JMenu();
        MnuPerformanceIndicator = new javax.swing.JMenuItem();
        MnuAlerts = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 185, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Bienvenido Jefe!!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(200, 185, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        MnuProfile.setText("Perfil");

        MnuLogOut.setText("Cerrar Sesión");
        MnuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuLogOutActionPerformed(evt);
            }
        });
        MnuProfile.add(MnuLogOut);

        MnuExit.setText("Cerrar Programa");
        MnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuExitActionPerformed(evt);
            }
        });
        MnuProfile.add(MnuExit);

        jMenuBar1.add(MnuProfile);

        MnuClient.setText("Clientes");

        MnuManageCustomer.setText("Administrar Clientes");
        MnuManageCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuManageCustomerActionPerformed(evt);
            }
        });
        MnuClient.add(MnuManageCustomer);

        jMenuItem1.setText("Ver Facturas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MnuClient.add(jMenuItem1);

        jMenuBar1.add(MnuClient);

        MnuTask.setText("Tareas");

        MnuManageTask.setText("Administrar Tareas");
        MnuManageTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuManageTaskActionPerformed(evt);
            }
        });
        MnuTask.add(MnuManageTask);

        jMenuItem2.setText("Añadir Tarea");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MnuTask.add(jMenuItem2);

        jMenuBar1.add(MnuTask);

        MnuAssistant.setText("Assistentes");

        MnuPerformanceIndicator.setText("Ver Indicadores de Rendimiento");
        MnuPerformanceIndicator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuPerformanceIndicatorActionPerformed(evt);
            }
        });
        MnuAssistant.add(MnuPerformanceIndicator);

        MnuAlerts.setText("Ver Alertas");
        MnuAlerts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuAlertsActionPerformed(evt);
            }
        });
        MnuAssistant.add(MnuAlerts);

        jMenuBar1.add(MnuAssistant);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MnuExitActionPerformed

    private void MnuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuLogOutActionPerformed

        FrmAlertSystemLogin frmAlertSystemLogin = new FrmAlertSystemLogin();
        frmAlertSystemLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MnuLogOutActionPerformed

    private void MnuManageCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuManageCustomerActionPerformed
        FrmManageCustomer frmManageCustomer = new FrmManageCustomer();
        frmManageCustomer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MnuManageCustomerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmInvoice frmInvoice = new FrmInvoice();
        frmInvoice.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MnuManageTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuManageTaskActionPerformed
        FrmManageTask frmManageTask = new FrmManageTask();
        frmManageTask.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_MnuManageTaskActionPerformed

    private void MnuPerformanceIndicatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuPerformanceIndicatorActionPerformed
        FrmPerformanceIndicator frmPerformanceIndicator = new FrmPerformanceIndicator();
        frmPerformanceIndicator.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MnuPerformanceIndicatorActionPerformed

    private void MnuAlertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAlertsActionPerformed
        FrmSeeMyAlerts frmSeeMyAlerts = new FrmSeeMyAlerts();
        frmSeeMyAlerts.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_MnuAlertsActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmTask frmTask = new FrmTask();
        frmTask.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAlertSystemMenuBoss().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuAlerts;
    private javax.swing.JMenu MnuAssistant;
    private javax.swing.JMenu MnuClient;
    private javax.swing.JMenuItem MnuExit;
    private javax.swing.JMenuItem MnuLogOut;
    private javax.swing.JMenuItem MnuManageCustomer;
    private javax.swing.JMenuItem MnuManageTask;
    private javax.swing.JMenuItem MnuPerformanceIndicator;
    private javax.swing.JMenu MnuProfile;
    private javax.swing.JMenu MnuTask;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
